name: Pipeline de Build e Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Clonar o Repositório (Igual ao anterior)
      - name: 1. Clonando o repositório
        uses: actions/checkout@v3
        
      # Passo 2: Construir a Imagem Docker (Igual ao anterior)
      - name: 2. Build da imagem Docker
        run: docker build . --file Dockerfile --tag minha-app:${{ github.sha }}

      # Passo 3: Teste Simples da Imagem (Opcional, mas bom manter)
      - name: 3. Teste simples da imagem
        run: docker run -d --name test-container minha-app:${{ github.sha }} && docker stop test-container

      # --- NOVO PASSO PARA PONTOS EXTRAS ---
      # Passo 4: Scan de Vulnerabilidades com Trivy
      # Este passo verifica se a nossa "caixa mágica" (imagem Docker)
      # tem alguma brecha de segurança conhecida.
      - name: 4. Scan de vulnerabilidades da imagem
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minha-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0' # Para não falhar o pipeline se encontrar algo
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'