# Forçando a re-sincronização do workflow em 26/09/2025

name: Pipeline Profissional de CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Clonando o repositório
        uses: actions/checkout@v3

      - name: 2. Lint do código com ESLint
        run: |
          npm install
          npm run lint

      - name: 3. Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Build e Push da imagem Docker
        uses: docker/build-and-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: 5. Teste simples da imagem
        run: docker run -d --name test-container ghcr.io/${{ github.repository }}:${{ github.sha }} && docker stop test-container

      - name: 6. Scan de vulnerabilidades da imagem
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'