# Nome do nosso pipeline
name: Pipeline de Build e Deploy

# Gatilho: Este pipeline vai rodar sempre que houver um "push" 
# (envio de código) para a branch "main".
on:
  push:
    branches: [ "main" ]

# Tarefas a serem executadas
jobs:
  # Nome da nossa primeira (e única) tarefa
  build-and-deploy:
    # A máquina virtual que o GitHub vai usar para rodar os passos
    runs-on: ubuntu-latest

    # Os passos da nossa linha de montagem
    steps:
      # Passo 1: Clonar o Repositório (Pegar o código)
      # O robô precisa baixar o código do repositório para poder trabalhar com ele.
      - name: 1. Clonando o repositório
        uses: actions/checkout@v3

      # Passo 2: Construir a Imagem Docker (Montar a "caixa mágica")
      # Aqui ele vai ler nosso Dockerfile e criar o pacote da aplicação.
      # A "tag" é como uma etiqueta de versão para nossa imagem.
      - name: 2. Build da imagem Docker
        run: docker build . --file Dockerfile --tag minha-app

      # Passo 3 (Simulado): Teste Simples (Verificar se a "caixa" funciona)
      # Este é um teste muito básico: tentamos rodar a imagem que acabamos de criar.
      # Se o comando rodar sem erro, o passo passa.
      - name: 3. Teste simples da imagem
        run: docker run -d --name test-container minha-app && docker stop test-container